AudioCraft:
  # MusicGen 
  ttm_model_size: melody # [small, medium, large]
  # AudioGen 
  tta_model_size: medium # [medium]

Text-to-Speech:
  # Bark
  speed: 1.05

Speech-Restoration:
  # VoiceFixer
  Enable: True

AudioLDM:
  model_size: audioldm-m-full